### ISSUE TITLE
How to throw a 500 error from ~gress controllers

### ISSUE THREAD

**Issue by always-akshat** [sleelin/scimmy-routers#12]
Based on the documentation/code, it looks like the right way to throw errors is to use the `SCIMMY.Types.Error`. This expects a `scimType` and `status` which is then handled and converted into a `SCIMMY.Messages.Error` type [here](https://github.com/scimmyjs/scimmy-routers/blob/ef68965cac80f26c26a5dd9393df8683b5acdef2/src/routers/resources.js#L24)

The problem with using the `SCIMMY.Types.Error` constructor is that it doesn't support any _scimType_ for statusCode 500.

What is the recommended way to throw a 500 error?

**Comment by always-akshat** [comment]
Ok, so this worked for me

```ts
import { SCIMMY } from "scimmy-routers";

const scimError = new SCIMMY.Types.Error(
      500,
      undefined as any as string,
      "Internal Server Error. Please try again later."
);
 ```

**Comment by sleelin** [comment]
Hi @always-akshat,

As you pointed out, there's no _scimType_ for a 500 error. This is because the _scimType_ property is primarily used to indicate the type of SCIM protocol issue encountered in a request that resulted in a `400 Bad Request` response (as well as `409 Conflict` and `413 Payload Too Large` responses with values of "uniqueness" and "tooMany" respectively).

The snippet you provided in your follow-up comment should allow you to throw a 500 error that gets translated into the SCIM protocol format, but as far as I'm aware, TypeScript should also let you omit the typing of the _scimType_ parameter:
```ts
throw new SCIMMY.Types.Error(500, undefined, "Internal Server Error. Please try again later.");
```

Thanks,
Sam
