### ISSUE TITLE
Getting Error When testing with Postman : Expected 'data' parameter to be an object in SchemaDefinition instance

### ISSUE THREAD

**Issue by ankidev0510** [sleelin/scimmy-routers#18]
I am using https://github.com/scimmyjs along with [scimmy-routers](https://github.com/scimmyjs/scimmy-routers) for SCIM implementation but when testing using postman provided by Microsoft, I am always getting below error

```json
{
    "schemas": [
        "urn:ietf:params:scim:api:messages:2.0:Error"
    ],
    "status": "400",
    "scimType": "invalidValue",
    "detail": "Expected 'data' parameter to be an object in SchemaDefinition instance"
}
```

The POST request I am using with /Users

```json
{
    "schemas": [
        "urn:ietf:params:scim:schemas:core:2.0:User"
    ],
    "externalId": "${__UUID}",
    "meta": {
        "resourceType": "User"
    },
    "userName": "UserName123",
    "name": {
        "formatted": "Ryan Leenay",
        "familyName": "Leenay",
        "givenName": "Ryan"
    },
    "displayName": "BobIsAmazing",
    "active": true,
    "emails": [
        {
            "value": "testing@bob.com",
            "type": "work",
            "primary": true
        },
        {
            "value": "testinghome@bob.com",
            "type": "home",
            "primary": false
        }
    ]
}
```

I am using Node JS Express. How can I resolve it any quick solution? What I am doing wrong below is the code for implementation

```js
const express = require("express");
const SCIMMY = require("scimmy");
const { default: SCIMMYRouters } = require("scimmy-routers");
const jwt = require("jsonwebtoken");
const bodyParser = require("body-parser");
const dotenv = require("dotenv");
const { userSchemaDef } = require("./schema");
dotenv.config();

const app = express();

// Custom SCIM+JSON body parser middleware
const scimJsonParser = bodyParser.json({ type: "application/scim+json" });

app.use(express.json());

// Apply middleware to SCIM routes
app.use("/scim/v2", scimJsonParser, (req, res, next) => {
  next();
});

SCIMMY.Resources.declare(SCIMMY.Resources.User, {
  schema: userSchemaDef,
  ingress: (resource, data) => {
    console.log(`Request to create/edit user ${JSON.stringify(resource)}, ${JSON.stringify(data)}`);
    let user = new SCIMMY.Schemas.User(data);
    console.log(`Create user ${JSON.stringify(user)}`);
  },
  egress: (resource) => {
    console.log(`Request to read user ${JSON.stringify(resource)}`);
  },
  degress: (resource) => {
    console.log(`Request to delete user ${resource}`);
  },
});

let authScheme = {
  type: "bearer",
  handler: (request, response) => {
    console.log("Inside auth check");
    const authHeader = request.header("Authorization");
    if (!authHeader?.startsWith("Bearer ")) {
      throw new Error("Authorization not detected!");
    } else {
      const token = authHeader.split(" ")[1];
      jwt.verify(token, process.env.SECRET_KEY, (err, user) => {
        if (err) throw new Error("Authorization failed");
        return token;
      });
    }
  },
};

app.use("/scim/v2", new SCIMMYRouters(authScheme));

app.post("/Token", (req, res) => {
  const user = { id: 1, username: "testuser" }; // Mock user
  const token = jwt.sign({ user }, process.env.SECRET_KEY, { expiresIn: "1h" });
  res.json({ token });
});

app.get("/", (req, res) => {
  res.send("Welcome to the SCIM server! v2");
});

const PORT = process.env.PORT || 8080;
app.listen(PORT, () => {
  console.log(`Server is running on http://localhost:${PORT}`);
});
```

Node JS version 16+

Thanks in advance

**Comment by sleelin** [comment]
Hi @ankidev0510,  
Thanks for reaching out and providing your code snippet - there are a few things of note that I can provide assistance with.

**Firstly**, addressing the error message response you are getting. Errors at any point are caught by the SCIMMYRouters middleware, and sent back in the form of a SCIM Error Message as seen in the response you supplied. The underlying cause of the error, though, is in your ingress handler method. The `detail` property of the response informs us that the `data` supplied to a `SchemaDefinition` instance was not an object. As all the `SCIMMY.Schemas` classes have an underlying `SchemaDefinition` instance, this would seem to suggest that the error is being caused when you construct a new `SCIMMY.Schemas.User` instance in the handler. Removing this line, however, does not resolve the error, as the _actual cause_ is the absence of a returned value from the handler.

For examples of how your handlers should look, what arguments they receive, and what they should return, please see the [Type Definitions section](https://scimmyjs.github.io/SCIMMY.Types.Resource.html#typedefs) of the `SCIMMY.Types.Resource` page on the [SCIMMY Documentation](https://scimmyjs.github.io/) site. It's also worth mentioning that the ingress/egress/degress handlers for the bundled `SCIMMY.Resources` classes are intended to act as the interface between your database (or other data source), and the SCIMMY library, with the resource class handling creation of the corresponding `SCIMMY.Schemas` classes under the hood. This abstraction should mean that there's no need for any of your handlers to construct their own `SCIMMY.Schemas` class instances - the `data` argument in your ingress handler, for example, will already be an instance of the `SCIMMY.Schemas.User` class.

**Secondly**, when declaring a bundled resource class, such as the `SCIMMY.Resources.User` class, it is neither necessary, nor possible to include a custom schema in the declaration config. This is because the bundled resources are for well-known resource types from the SCIM protocol specification, and already define schemas that cover all the attributes for the resource from the specification.

As not every service will implement every attribute, or may include extension attributes not covered by the protocol, it's still possible to modify the bundled resource schemas. This is done in a couple of ways, depending on your needs. Extending a resource with a custom schema, for example, is covered [here in the SCIMMY.Resources documentation](https://scimmyjs.github.io/SCIMMY.Resources.html#extending-resource-types). If instead you needed to remove unsupported attributes from the resource schema, or add new custom attributes, this is done directly on the bundled `SCIMMY.Schemas` classes, and is covered [here in the SCIMMY.Schemas documentation](https://scimmyjs.github.io/SCIMMY.Schemas.html#modifying-definitions).

**Thirdly**, as it's a protocol-level requirement that messages are exchanged with the `application/scim+json` content type, this is already handled internally by the `SCIMMYRouters` middleware. This means that there is no need for you to manually do this in your app setup, and the following lines in your code can be removed entirely:
```diff
...
const app = express();

-// Custom SCIM+JSON body parser middleware
-const scimJsonParser = bodyParser.json({ type: "application/scim+json" });
-
app.use(express.json());

-// Apply middleware to SCIM routes
-app.use("/scim/v2", scimJsonParser, (req, res, next) => {
-  next();
-});
...
```

Note also that the built-in `express.json()` middleware is actually [a bundled implementation of the body-parser package](https://expressjs.com/en/api.html#express.json), introduced in Express v4.16, and if you are able to use it, you should be able to remove the body-parser dependency from your code entirely.

**Finally**, an observation on the use of CommonJS modules (i.e. `const x = require("x");`). Whilst SCIMMY and SCIMMYRouters both come with CommonJS implementations, they are transpiled from the ESM syntax (i.e. `import {x} from "x";`) they were written in, and included mainly for backwards compatibility reasons. JavaScript Modules (also known as ECMAScript Modules, or ESM for short) have been [widely available since June 2018](https://v8.dev/features/modules), and many prominent NPM packages have moved towards removing all support for CommonJS modules. Indeed, JavaScript Modules have been fully supported in Node.js since v13.2.0, released in November 2019. When writing new code, I would very strongly encourage you to leverage JavaScript Modules instead of CommonJS modules, where possible. If you're unsure of how they work or why you should use them, there are some really good guides available over at [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules) and [JavaScript.info](https://javascript.info/modules-intro) that cover this very thoroughly.

I hope the above is useful for you - if you have any further questions please do follow up.

Thanks,
Sam
