### ISSUE TITLE
How to return a FORBIDDEN http status?

### ISSUE THREAD

**Issue by fflorent** [sleelin/scimmy-routers#26]
## Context

I need to disallow to non-admin accessing some operations but still allowing accessing to others (for example disallowing accessing the users list but allowing doing information on themselves using `/Me`).

The `handler` function is meant to tell whether the user is authenticated, and to return the ID. But it is not meant to disallow accessing a resource. It also seems like when I raise any Error in the `handler`, a 401 status code is returned to the client ([source](https://github.com/scimmyjs/scimmy-routers/blob/d06f36e177f9990fee598187c639b5d3a6ef04b9/src/routers.js#L142)).

## Proposed solution

I wonder if the user id making the operation could not be passed to the SCIMMY handlers (`ingress`, `egress`, `degress`) for that purpose. I am not sure whether it should be passed along the `data` or the `resource` param.

Any thoughts? Or is there a proper way already in place for doing that?

Thanks in advance.

**Comment by fflorent** [comment]
I have found a way to do that: the `context`, which is given a request and returns an object that is passed to all handlers: `egress`, `degress` and `ingress`.

I achieved returning a 403 status code:
 - the controller is here: https://github.com/gristlabs/grist-core/pull/1199/files#diff-718d3e2193a1261bcf5cd6f6bba04e22bec1b0c4b162c6adbf0ae4847f107912R39-R46
 - the function that is called by the handlers and that raises a 403 Error: https://github.com/gristlabs/grist-core/pull/1199/files#diff-718d3e2193a1261bcf5cd6f6bba04e22bec1b0c4b162c6adbf0ae4847f107912R15-R20

**Comment by sleelin** [comment]
Hi @fflorent, apologies for the delay in answering this question.

To clarify, the `handler` method is intended to be used to determine whether a request has been made by an authenticated user, and if so, which specific user that may be. For ease of use, SCIMMYRouters will catch any errors thrown by the `handler` method, treat the request as _unauthenticated_, and respond with a `401 Unauthorized` message. More explicitly, this is because the request has been treated as though it has not been made with valid credentials. The `handler` method is not intended to be used to determine whether a specific request, made with valid credentials, is permitted.

For determining whether an authenticated request, with valid credentials, is _unauthorized_ (i.e. the user actually has permission to perform the action), there are a few different approaches you can take. Any `SCIMMY.Types.Error` exceptions thrown by the `context` method, which has access to the express request, will be appropriately handled. Similarly, `SCIMMY.Types.Error` exceptions thrown by the `ingress`/`egress`/`degress` handler methods, which have access to the value returned by the `context` method, will be handled.

With this in mind, I would recommend the `handler` method be used to deserialise a specific authenticated user, writing the value to the `req.user` property for use in the `context` method, which can safely raise permission errors. If details of the specific user that made the request are needed in the `ingress`/`egress`/`degress` handlers, they can be passed through using the return value of the `context` method (e.g. having the full user details by making the `context` method return the `req.user` value stored by the handler).

Let me know if this adequately answers your question, although based on your follow up comment and the linked snippets, it seems as though you may have already worked this answer out before I could get back to you.

Thanks,
Sam
